# Generated by Django 5.2.1 on 2025-07-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_entry_fqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='inbox',
            index=models.Index(fields=['is_processed'], name='app_inbox_is_proc_4c0f9e_idx'),
        ),
    ]
